//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGTerminal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monster
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int HealthPoints { get; set; }
        public int HitPoints { get; set; }
        public int DefensePoints { get; set; }
        public bool isFinal { get; set; }
        public int CoinDrop { get; set; }
        public bool Defeated { get; set; }
        public Nullable<int> itemID { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
