//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGTerminal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Coins { get; set; }
        public int HealthPoints { get; set; }
        public int HitPoints { get; set; }
        public bool isCurrent { get; set; }
        public int Score { get; set; }
    }
}
